zstyle ':zim:git' aliases-prefix 'g'

alias   ws='cd $HOME/workshop/'
alias   vm='docker run --rm --cap-add sys_ptrace -v `pwd`:/ctf -it reverse'
alias   ida='open -a ida'
alias   ida64='open -a ida64'
alias   ipy='ipython'
alias   klee="docker run --rm -v `pwd`:/ctf -it --ulimit='stack=-1:-1' klee/klee"
#alias   vs='open -a "Visual Studio Code"'
#alias   avdmanager='$HOME/Library/Android/sdk/tools/bin/avdmanager'
#alias   emulator='$HOME/Library/Android/sdk/tools/emulator'
